name: Maven Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'  
        java-version: '21'       

    - name: List directories
      run: ls -la

    - name: cd into PetStoreAPITestingApp
      run: cd PetStoreAPITestingApp

    - name: List directories
      run: ls -la

    - name: Build with Maven (Skip tests)
      run: mvn clean install -DskipTests
